package jp.co.project.smart.autogen.model;

import java.util.Date;

public class ApiDefine {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_define.api_id
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    private String apiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_define.url
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_define.name
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_define.note
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_define.api_define
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    private Object apiDefine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_define.create_time
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_define.create_user
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_define.update_time
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_define.update_user
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_define.api_id
     *
     * @return the value of api_define.api_id
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    public String getApiId() {
        return apiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_define.api_id
     *
     * @param apiId the value for api_define.api_id
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    public void setApiId(String apiId) {
        this.apiId = apiId == null ? null : apiId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_define.url
     *
     * @return the value of api_define.url
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_define.url
     *
     * @param url the value for api_define.url
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_define.name
     *
     * @return the value of api_define.name
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_define.name
     *
     * @param name the value for api_define.name
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_define.note
     *
     * @return the value of api_define.note
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_define.note
     *
     * @param note the value for api_define.note
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_define.api_define
     *
     * @return the value of api_define.api_define
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    public Object getApiDefine() {
        return apiDefine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_define.api_define
     *
     * @param apiDefine the value for api_define.api_define
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    public void setApiDefine(Object apiDefine) {
        this.apiDefine = apiDefine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_define.create_time
     *
     * @return the value of api_define.create_time
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_define.create_time
     *
     * @param createTime the value for api_define.create_time
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_define.create_user
     *
     * @return the value of api_define.create_user
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_define.create_user
     *
     * @param createUser the value for api_define.create_user
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_define.update_time
     *
     * @return the value of api_define.update_time
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_define.update_time
     *
     * @param updateTime the value for api_define.update_time
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_define.update_user
     *
     * @return the value of api_define.update_user
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_define.update_user
     *
     * @param updateUser the value for api_define.update_user
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }
}