package jp.co.project.smart.autogen.model;

import java.util.Date;

public class CodeMaster {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_master.code_id
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private Integer codeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_master.word_id
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private Integer wordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_master.physical_code_name
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private String physicalCodeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_master.logic_code_name
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private String logicCodeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_master.create_time
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_master.create_user
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_master.update_time
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_master.update_user
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_master.code_id
     *
     * @return the value of code_master.code_id
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public Integer getCodeId() {
        return codeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_master.code_id
     *
     * @param codeId the value for code_master.code_id
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setCodeId(Integer codeId) {
        this.codeId = codeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_master.word_id
     *
     * @return the value of code_master.word_id
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public Integer getWordId() {
        return wordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_master.word_id
     *
     * @param wordId the value for code_master.word_id
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setWordId(Integer wordId) {
        this.wordId = wordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_master.physical_code_name
     *
     * @return the value of code_master.physical_code_name
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public String getPhysicalCodeName() {
        return physicalCodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_master.physical_code_name
     *
     * @param physicalCodeName the value for code_master.physical_code_name
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setPhysicalCodeName(String physicalCodeName) {
        this.physicalCodeName = physicalCodeName == null ? null : physicalCodeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_master.logic_code_name
     *
     * @return the value of code_master.logic_code_name
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public String getLogicCodeName() {
        return logicCodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_master.logic_code_name
     *
     * @param logicCodeName the value for code_master.logic_code_name
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setLogicCodeName(String logicCodeName) {
        this.logicCodeName = logicCodeName == null ? null : logicCodeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_master.create_time
     *
     * @return the value of code_master.create_time
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_master.create_time
     *
     * @param createTime the value for code_master.create_time
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_master.create_user
     *
     * @return the value of code_master.create_user
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_master.create_user
     *
     * @param createUser the value for code_master.create_user
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_master.update_time
     *
     * @return the value of code_master.update_time
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_master.update_time
     *
     * @param updateTime the value for code_master.update_time
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_master.update_user
     *
     * @return the value of code_master.update_user
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_master.update_user
     *
     * @param updateUser the value for code_master.update_user
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }
}