package jp.co.project.smart.autogen.model;

import java.util.Date;

public class CodeValueMaster {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_value_master.code_id
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private Integer codeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_value_master.code_no
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private Integer codeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_value_master.value_physical_name
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private String valuePhysicalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_value_master.value_logic_name
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private String valueLogicName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_value_master.code_value
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private String codeValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_value_master.create_time
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_value_master.create_user
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_value_master.update_time
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_value_master.update_user
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_value_master.code_id
     *
     * @return the value of code_value_master.code_id
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public Integer getCodeId() {
        return codeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_value_master.code_id
     *
     * @param codeId the value for code_value_master.code_id
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setCodeId(Integer codeId) {
        this.codeId = codeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_value_master.code_no
     *
     * @return the value of code_value_master.code_no
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public Integer getCodeNo() {
        return codeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_value_master.code_no
     *
     * @param codeNo the value for code_value_master.code_no
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setCodeNo(Integer codeNo) {
        this.codeNo = codeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_value_master.value_physical_name
     *
     * @return the value of code_value_master.value_physical_name
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public String getValuePhysicalName() {
        return valuePhysicalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_value_master.value_physical_name
     *
     * @param valuePhysicalName the value for code_value_master.value_physical_name
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setValuePhysicalName(String valuePhysicalName) {
        this.valuePhysicalName = valuePhysicalName == null ? null : valuePhysicalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_value_master.value_logic_name
     *
     * @return the value of code_value_master.value_logic_name
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public String getValueLogicName() {
        return valueLogicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_value_master.value_logic_name
     *
     * @param valueLogicName the value for code_value_master.value_logic_name
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setValueLogicName(String valueLogicName) {
        this.valueLogicName = valueLogicName == null ? null : valueLogicName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_value_master.code_value
     *
     * @return the value of code_value_master.code_value
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public String getCodeValue() {
        return codeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_value_master.code_value
     *
     * @param codeValue the value for code_value_master.code_value
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setCodeValue(String codeValue) {
        this.codeValue = codeValue == null ? null : codeValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_value_master.create_time
     *
     * @return the value of code_value_master.create_time
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_value_master.create_time
     *
     * @param createTime the value for code_value_master.create_time
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_value_master.create_user
     *
     * @return the value of code_value_master.create_user
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_value_master.create_user
     *
     * @param createUser the value for code_value_master.create_user
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_value_master.update_time
     *
     * @return the value of code_value_master.update_time
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_value_master.update_time
     *
     * @param updateTime the value for code_value_master.update_time
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_value_master.update_user
     *
     * @return the value of code_value_master.update_user
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_value_master.update_user
     *
     * @param updateUser the value for code_value_master.update_user
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }
}