package jp.co.project.smart.autogen.model;

import java.util.Date;

public class ColumnMaster {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_master.column_id
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private Integer columnId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_master.table_id
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private Integer tableId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_master.word_id
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private Integer wordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_master.seq_no
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private Integer seqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_master.description
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_master.unique_key_name
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private Object uniqueKeyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_master.column_constraint
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private Object columnConstraint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_master.foreign_key_flg
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private Boolean foreignKeyFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_master.not_null_flg
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private Boolean notNullFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_master.primary_key_flg
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private Boolean primaryKeyFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_master.unique_key_flg
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private Boolean uniqueKeyFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_master.create_time
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_master.create_user
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_master.update_time
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_master.update_user
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_master.column_id
     *
     * @return the value of column_master.column_id
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public Integer getColumnId() {
        return columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_master.column_id
     *
     * @param columnId the value for column_master.column_id
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setColumnId(Integer columnId) {
        this.columnId = columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_master.table_id
     *
     * @return the value of column_master.table_id
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public Integer getTableId() {
        return tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_master.table_id
     *
     * @param tableId the value for column_master.table_id
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setTableId(Integer tableId) {
        this.tableId = tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_master.word_id
     *
     * @return the value of column_master.word_id
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public Integer getWordId() {
        return wordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_master.word_id
     *
     * @param wordId the value for column_master.word_id
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setWordId(Integer wordId) {
        this.wordId = wordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_master.seq_no
     *
     * @return the value of column_master.seq_no
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public Integer getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_master.seq_no
     *
     * @param seqNo the value for column_master.seq_no
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setSeqNo(Integer seqNo) {
        this.seqNo = seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_master.description
     *
     * @return the value of column_master.description
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_master.description
     *
     * @param description the value for column_master.description
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_master.unique_key_name
     *
     * @return the value of column_master.unique_key_name
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public Object getUniqueKeyName() {
        return uniqueKeyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_master.unique_key_name
     *
     * @param uniqueKeyName the value for column_master.unique_key_name
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setUniqueKeyName(Object uniqueKeyName) {
        this.uniqueKeyName = uniqueKeyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_master.column_constraint
     *
     * @return the value of column_master.column_constraint
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public Object getColumnConstraint() {
        return columnConstraint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_master.column_constraint
     *
     * @param columnConstraint the value for column_master.column_constraint
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setColumnConstraint(Object columnConstraint) {
        this.columnConstraint = columnConstraint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_master.foreign_key_flg
     *
     * @return the value of column_master.foreign_key_flg
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public Boolean getForeignKeyFlg() {
        return foreignKeyFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_master.foreign_key_flg
     *
     * @param foreignKeyFlg the value for column_master.foreign_key_flg
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setForeignKeyFlg(Boolean foreignKeyFlg) {
        this.foreignKeyFlg = foreignKeyFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_master.not_null_flg
     *
     * @return the value of column_master.not_null_flg
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public Boolean getNotNullFlg() {
        return notNullFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_master.not_null_flg
     *
     * @param notNullFlg the value for column_master.not_null_flg
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setNotNullFlg(Boolean notNullFlg) {
        this.notNullFlg = notNullFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_master.primary_key_flg
     *
     * @return the value of column_master.primary_key_flg
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public Boolean getPrimaryKeyFlg() {
        return primaryKeyFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_master.primary_key_flg
     *
     * @param primaryKeyFlg the value for column_master.primary_key_flg
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setPrimaryKeyFlg(Boolean primaryKeyFlg) {
        this.primaryKeyFlg = primaryKeyFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_master.unique_key_flg
     *
     * @return the value of column_master.unique_key_flg
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public Boolean getUniqueKeyFlg() {
        return uniqueKeyFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_master.unique_key_flg
     *
     * @param uniqueKeyFlg the value for column_master.unique_key_flg
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setUniqueKeyFlg(Boolean uniqueKeyFlg) {
        this.uniqueKeyFlg = uniqueKeyFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_master.create_time
     *
     * @return the value of column_master.create_time
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_master.create_time
     *
     * @param createTime the value for column_master.create_time
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_master.create_user
     *
     * @return the value of column_master.create_user
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_master.create_user
     *
     * @param createUser the value for column_master.create_user
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_master.update_time
     *
     * @return the value of column_master.update_time
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_master.update_time
     *
     * @param updateTime the value for column_master.update_time
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_master.update_user
     *
     * @return the value of column_master.update_user
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_master.update_user
     *
     * @param updateUser the value for column_master.update_user
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }
}