package jp.co.project.smart.autogen.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ColumnMasterExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table column_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table column_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table column_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public ColumnMasterExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table column_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andColumnIdIsNull() {
            addCriterion("column_id is null");
            return (Criteria) this;
        }

        public Criteria andColumnIdIsNotNull() {
            addCriterion("column_id is not null");
            return (Criteria) this;
        }

        public Criteria andColumnIdEqualTo(Integer value) {
            addCriterion("column_id =", value, "columnId");
            return (Criteria) this;
        }

        public Criteria andColumnIdNotEqualTo(Integer value) {
            addCriterion("column_id <>", value, "columnId");
            return (Criteria) this;
        }

        public Criteria andColumnIdGreaterThan(Integer value) {
            addCriterion("column_id >", value, "columnId");
            return (Criteria) this;
        }

        public Criteria andColumnIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("column_id >=", value, "columnId");
            return (Criteria) this;
        }

        public Criteria andColumnIdLessThan(Integer value) {
            addCriterion("column_id <", value, "columnId");
            return (Criteria) this;
        }

        public Criteria andColumnIdLessThanOrEqualTo(Integer value) {
            addCriterion("column_id <=", value, "columnId");
            return (Criteria) this;
        }

        public Criteria andColumnIdIn(List<Integer> values) {
            addCriterion("column_id in", values, "columnId");
            return (Criteria) this;
        }

        public Criteria andColumnIdNotIn(List<Integer> values) {
            addCriterion("column_id not in", values, "columnId");
            return (Criteria) this;
        }

        public Criteria andColumnIdBetween(Integer value1, Integer value2) {
            addCriterion("column_id between", value1, value2, "columnId");
            return (Criteria) this;
        }

        public Criteria andColumnIdNotBetween(Integer value1, Integer value2) {
            addCriterion("column_id not between", value1, value2, "columnId");
            return (Criteria) this;
        }

        public Criteria andTableIdIsNull() {
            addCriterion("table_id is null");
            return (Criteria) this;
        }

        public Criteria andTableIdIsNotNull() {
            addCriterion("table_id is not null");
            return (Criteria) this;
        }

        public Criteria andTableIdEqualTo(Integer value) {
            addCriterion("table_id =", value, "tableId");
            return (Criteria) this;
        }

        public Criteria andTableIdNotEqualTo(Integer value) {
            addCriterion("table_id <>", value, "tableId");
            return (Criteria) this;
        }

        public Criteria andTableIdGreaterThan(Integer value) {
            addCriterion("table_id >", value, "tableId");
            return (Criteria) this;
        }

        public Criteria andTableIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("table_id >=", value, "tableId");
            return (Criteria) this;
        }

        public Criteria andTableIdLessThan(Integer value) {
            addCriterion("table_id <", value, "tableId");
            return (Criteria) this;
        }

        public Criteria andTableIdLessThanOrEqualTo(Integer value) {
            addCriterion("table_id <=", value, "tableId");
            return (Criteria) this;
        }

        public Criteria andTableIdIn(List<Integer> values) {
            addCriterion("table_id in", values, "tableId");
            return (Criteria) this;
        }

        public Criteria andTableIdNotIn(List<Integer> values) {
            addCriterion("table_id not in", values, "tableId");
            return (Criteria) this;
        }

        public Criteria andTableIdBetween(Integer value1, Integer value2) {
            addCriterion("table_id between", value1, value2, "tableId");
            return (Criteria) this;
        }

        public Criteria andTableIdNotBetween(Integer value1, Integer value2) {
            addCriterion("table_id not between", value1, value2, "tableId");
            return (Criteria) this;
        }

        public Criteria andWordIdIsNull() {
            addCriterion("word_id is null");
            return (Criteria) this;
        }

        public Criteria andWordIdIsNotNull() {
            addCriterion("word_id is not null");
            return (Criteria) this;
        }

        public Criteria andWordIdEqualTo(Integer value) {
            addCriterion("word_id =", value, "wordId");
            return (Criteria) this;
        }

        public Criteria andWordIdNotEqualTo(Integer value) {
            addCriterion("word_id <>", value, "wordId");
            return (Criteria) this;
        }

        public Criteria andWordIdGreaterThan(Integer value) {
            addCriterion("word_id >", value, "wordId");
            return (Criteria) this;
        }

        public Criteria andWordIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("word_id >=", value, "wordId");
            return (Criteria) this;
        }

        public Criteria andWordIdLessThan(Integer value) {
            addCriterion("word_id <", value, "wordId");
            return (Criteria) this;
        }

        public Criteria andWordIdLessThanOrEqualTo(Integer value) {
            addCriterion("word_id <=", value, "wordId");
            return (Criteria) this;
        }

        public Criteria andWordIdIn(List<Integer> values) {
            addCriterion("word_id in", values, "wordId");
            return (Criteria) this;
        }

        public Criteria andWordIdNotIn(List<Integer> values) {
            addCriterion("word_id not in", values, "wordId");
            return (Criteria) this;
        }

        public Criteria andWordIdBetween(Integer value1, Integer value2) {
            addCriterion("word_id between", value1, value2, "wordId");
            return (Criteria) this;
        }

        public Criteria andWordIdNotBetween(Integer value1, Integer value2) {
            addCriterion("word_id not between", value1, value2, "wordId");
            return (Criteria) this;
        }

        public Criteria andSeqNoIsNull() {
            addCriterion("seq_no is null");
            return (Criteria) this;
        }

        public Criteria andSeqNoIsNotNull() {
            addCriterion("seq_no is not null");
            return (Criteria) this;
        }

        public Criteria andSeqNoEqualTo(Integer value) {
            addCriterion("seq_no =", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoNotEqualTo(Integer value) {
            addCriterion("seq_no <>", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoGreaterThan(Integer value) {
            addCriterion("seq_no >", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("seq_no >=", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoLessThan(Integer value) {
            addCriterion("seq_no <", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoLessThanOrEqualTo(Integer value) {
            addCriterion("seq_no <=", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoIn(List<Integer> values) {
            addCriterion("seq_no in", values, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoNotIn(List<Integer> values) {
            addCriterion("seq_no not in", values, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoBetween(Integer value1, Integer value2) {
            addCriterion("seq_no between", value1, value2, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoNotBetween(Integer value1, Integer value2) {
            addCriterion("seq_no not between", value1, value2, "seqNo");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andUniqueKeyNameIsNull() {
            addCriterion("unique_key_name is null");
            return (Criteria) this;
        }

        public Criteria andUniqueKeyNameIsNotNull() {
            addCriterion("unique_key_name is not null");
            return (Criteria) this;
        }

        public Criteria andUniqueKeyNameEqualTo(Object value) {
            addCriterion("unique_key_name =", value, "uniqueKeyName");
            return (Criteria) this;
        }

        public Criteria andUniqueKeyNameNotEqualTo(Object value) {
            addCriterion("unique_key_name <>", value, "uniqueKeyName");
            return (Criteria) this;
        }

        public Criteria andUniqueKeyNameGreaterThan(Object value) {
            addCriterion("unique_key_name >", value, "uniqueKeyName");
            return (Criteria) this;
        }

        public Criteria andUniqueKeyNameGreaterThanOrEqualTo(Object value) {
            addCriterion("unique_key_name >=", value, "uniqueKeyName");
            return (Criteria) this;
        }

        public Criteria andUniqueKeyNameLessThan(Object value) {
            addCriterion("unique_key_name <", value, "uniqueKeyName");
            return (Criteria) this;
        }

        public Criteria andUniqueKeyNameLessThanOrEqualTo(Object value) {
            addCriterion("unique_key_name <=", value, "uniqueKeyName");
            return (Criteria) this;
        }

        public Criteria andUniqueKeyNameIn(List<Object> values) {
            addCriterion("unique_key_name in", values, "uniqueKeyName");
            return (Criteria) this;
        }

        public Criteria andUniqueKeyNameNotIn(List<Object> values) {
            addCriterion("unique_key_name not in", values, "uniqueKeyName");
            return (Criteria) this;
        }

        public Criteria andUniqueKeyNameBetween(Object value1, Object value2) {
            addCriterion("unique_key_name between", value1, value2, "uniqueKeyName");
            return (Criteria) this;
        }

        public Criteria andUniqueKeyNameNotBetween(Object value1, Object value2) {
            addCriterion("unique_key_name not between", value1, value2, "uniqueKeyName");
            return (Criteria) this;
        }

        public Criteria andColumnConstraintIsNull() {
            addCriterion("column_constraint is null");
            return (Criteria) this;
        }

        public Criteria andColumnConstraintIsNotNull() {
            addCriterion("column_constraint is not null");
            return (Criteria) this;
        }

        public Criteria andColumnConstraintEqualTo(Object value) {
            addCriterion("column_constraint =", value, "columnConstraint");
            return (Criteria) this;
        }

        public Criteria andColumnConstraintNotEqualTo(Object value) {
            addCriterion("column_constraint <>", value, "columnConstraint");
            return (Criteria) this;
        }

        public Criteria andColumnConstraintGreaterThan(Object value) {
            addCriterion("column_constraint >", value, "columnConstraint");
            return (Criteria) this;
        }

        public Criteria andColumnConstraintGreaterThanOrEqualTo(Object value) {
            addCriterion("column_constraint >=", value, "columnConstraint");
            return (Criteria) this;
        }

        public Criteria andColumnConstraintLessThan(Object value) {
            addCriterion("column_constraint <", value, "columnConstraint");
            return (Criteria) this;
        }

        public Criteria andColumnConstraintLessThanOrEqualTo(Object value) {
            addCriterion("column_constraint <=", value, "columnConstraint");
            return (Criteria) this;
        }

        public Criteria andColumnConstraintIn(List<Object> values) {
            addCriterion("column_constraint in", values, "columnConstraint");
            return (Criteria) this;
        }

        public Criteria andColumnConstraintNotIn(List<Object> values) {
            addCriterion("column_constraint not in", values, "columnConstraint");
            return (Criteria) this;
        }

        public Criteria andColumnConstraintBetween(Object value1, Object value2) {
            addCriterion("column_constraint between", value1, value2, "columnConstraint");
            return (Criteria) this;
        }

        public Criteria andColumnConstraintNotBetween(Object value1, Object value2) {
            addCriterion("column_constraint not between", value1, value2, "columnConstraint");
            return (Criteria) this;
        }

        public Criteria andForeignKeyFlgIsNull() {
            addCriterion("foreign_key_flg is null");
            return (Criteria) this;
        }

        public Criteria andForeignKeyFlgIsNotNull() {
            addCriterion("foreign_key_flg is not null");
            return (Criteria) this;
        }

        public Criteria andForeignKeyFlgEqualTo(Boolean value) {
            addCriterion("foreign_key_flg =", value, "foreignKeyFlg");
            return (Criteria) this;
        }

        public Criteria andForeignKeyFlgNotEqualTo(Boolean value) {
            addCriterion("foreign_key_flg <>", value, "foreignKeyFlg");
            return (Criteria) this;
        }

        public Criteria andForeignKeyFlgGreaterThan(Boolean value) {
            addCriterion("foreign_key_flg >", value, "foreignKeyFlg");
            return (Criteria) this;
        }

        public Criteria andForeignKeyFlgGreaterThanOrEqualTo(Boolean value) {
            addCriterion("foreign_key_flg >=", value, "foreignKeyFlg");
            return (Criteria) this;
        }

        public Criteria andForeignKeyFlgLessThan(Boolean value) {
            addCriterion("foreign_key_flg <", value, "foreignKeyFlg");
            return (Criteria) this;
        }

        public Criteria andForeignKeyFlgLessThanOrEqualTo(Boolean value) {
            addCriterion("foreign_key_flg <=", value, "foreignKeyFlg");
            return (Criteria) this;
        }

        public Criteria andForeignKeyFlgIn(List<Boolean> values) {
            addCriterion("foreign_key_flg in", values, "foreignKeyFlg");
            return (Criteria) this;
        }

        public Criteria andForeignKeyFlgNotIn(List<Boolean> values) {
            addCriterion("foreign_key_flg not in", values, "foreignKeyFlg");
            return (Criteria) this;
        }

        public Criteria andForeignKeyFlgBetween(Boolean value1, Boolean value2) {
            addCriterion("foreign_key_flg between", value1, value2, "foreignKeyFlg");
            return (Criteria) this;
        }

        public Criteria andForeignKeyFlgNotBetween(Boolean value1, Boolean value2) {
            addCriterion("foreign_key_flg not between", value1, value2, "foreignKeyFlg");
            return (Criteria) this;
        }

        public Criteria andNotNullFlgIsNull() {
            addCriterion("not_null_flg is null");
            return (Criteria) this;
        }

        public Criteria andNotNullFlgIsNotNull() {
            addCriterion("not_null_flg is not null");
            return (Criteria) this;
        }

        public Criteria andNotNullFlgEqualTo(Boolean value) {
            addCriterion("not_null_flg =", value, "notNullFlg");
            return (Criteria) this;
        }

        public Criteria andNotNullFlgNotEqualTo(Boolean value) {
            addCriterion("not_null_flg <>", value, "notNullFlg");
            return (Criteria) this;
        }

        public Criteria andNotNullFlgGreaterThan(Boolean value) {
            addCriterion("not_null_flg >", value, "notNullFlg");
            return (Criteria) this;
        }

        public Criteria andNotNullFlgGreaterThanOrEqualTo(Boolean value) {
            addCriterion("not_null_flg >=", value, "notNullFlg");
            return (Criteria) this;
        }

        public Criteria andNotNullFlgLessThan(Boolean value) {
            addCriterion("not_null_flg <", value, "notNullFlg");
            return (Criteria) this;
        }

        public Criteria andNotNullFlgLessThanOrEqualTo(Boolean value) {
            addCriterion("not_null_flg <=", value, "notNullFlg");
            return (Criteria) this;
        }

        public Criteria andNotNullFlgIn(List<Boolean> values) {
            addCriterion("not_null_flg in", values, "notNullFlg");
            return (Criteria) this;
        }

        public Criteria andNotNullFlgNotIn(List<Boolean> values) {
            addCriterion("not_null_flg not in", values, "notNullFlg");
            return (Criteria) this;
        }

        public Criteria andNotNullFlgBetween(Boolean value1, Boolean value2) {
            addCriterion("not_null_flg between", value1, value2, "notNullFlg");
            return (Criteria) this;
        }

        public Criteria andNotNullFlgNotBetween(Boolean value1, Boolean value2) {
            addCriterion("not_null_flg not between", value1, value2, "notNullFlg");
            return (Criteria) this;
        }

        public Criteria andPrimaryKeyFlgIsNull() {
            addCriterion("primary_key_flg is null");
            return (Criteria) this;
        }

        public Criteria andPrimaryKeyFlgIsNotNull() {
            addCriterion("primary_key_flg is not null");
            return (Criteria) this;
        }

        public Criteria andPrimaryKeyFlgEqualTo(Boolean value) {
            addCriterion("primary_key_flg =", value, "primaryKeyFlg");
            return (Criteria) this;
        }

        public Criteria andPrimaryKeyFlgNotEqualTo(Boolean value) {
            addCriterion("primary_key_flg <>", value, "primaryKeyFlg");
            return (Criteria) this;
        }

        public Criteria andPrimaryKeyFlgGreaterThan(Boolean value) {
            addCriterion("primary_key_flg >", value, "primaryKeyFlg");
            return (Criteria) this;
        }

        public Criteria andPrimaryKeyFlgGreaterThanOrEqualTo(Boolean value) {
            addCriterion("primary_key_flg >=", value, "primaryKeyFlg");
            return (Criteria) this;
        }

        public Criteria andPrimaryKeyFlgLessThan(Boolean value) {
            addCriterion("primary_key_flg <", value, "primaryKeyFlg");
            return (Criteria) this;
        }

        public Criteria andPrimaryKeyFlgLessThanOrEqualTo(Boolean value) {
            addCriterion("primary_key_flg <=", value, "primaryKeyFlg");
            return (Criteria) this;
        }

        public Criteria andPrimaryKeyFlgIn(List<Boolean> values) {
            addCriterion("primary_key_flg in", values, "primaryKeyFlg");
            return (Criteria) this;
        }

        public Criteria andPrimaryKeyFlgNotIn(List<Boolean> values) {
            addCriterion("primary_key_flg not in", values, "primaryKeyFlg");
            return (Criteria) this;
        }

        public Criteria andPrimaryKeyFlgBetween(Boolean value1, Boolean value2) {
            addCriterion("primary_key_flg between", value1, value2, "primaryKeyFlg");
            return (Criteria) this;
        }

        public Criteria andPrimaryKeyFlgNotBetween(Boolean value1, Boolean value2) {
            addCriterion("primary_key_flg not between", value1, value2, "primaryKeyFlg");
            return (Criteria) this;
        }

        public Criteria andUniqueKeyFlgIsNull() {
            addCriterion("unique_key_flg is null");
            return (Criteria) this;
        }

        public Criteria andUniqueKeyFlgIsNotNull() {
            addCriterion("unique_key_flg is not null");
            return (Criteria) this;
        }

        public Criteria andUniqueKeyFlgEqualTo(Boolean value) {
            addCriterion("unique_key_flg =", value, "uniqueKeyFlg");
            return (Criteria) this;
        }

        public Criteria andUniqueKeyFlgNotEqualTo(Boolean value) {
            addCriterion("unique_key_flg <>", value, "uniqueKeyFlg");
            return (Criteria) this;
        }

        public Criteria andUniqueKeyFlgGreaterThan(Boolean value) {
            addCriterion("unique_key_flg >", value, "uniqueKeyFlg");
            return (Criteria) this;
        }

        public Criteria andUniqueKeyFlgGreaterThanOrEqualTo(Boolean value) {
            addCriterion("unique_key_flg >=", value, "uniqueKeyFlg");
            return (Criteria) this;
        }

        public Criteria andUniqueKeyFlgLessThan(Boolean value) {
            addCriterion("unique_key_flg <", value, "uniqueKeyFlg");
            return (Criteria) this;
        }

        public Criteria andUniqueKeyFlgLessThanOrEqualTo(Boolean value) {
            addCriterion("unique_key_flg <=", value, "uniqueKeyFlg");
            return (Criteria) this;
        }

        public Criteria andUniqueKeyFlgIn(List<Boolean> values) {
            addCriterion("unique_key_flg in", values, "uniqueKeyFlg");
            return (Criteria) this;
        }

        public Criteria andUniqueKeyFlgNotIn(List<Boolean> values) {
            addCriterion("unique_key_flg not in", values, "uniqueKeyFlg");
            return (Criteria) this;
        }

        public Criteria andUniqueKeyFlgBetween(Boolean value1, Boolean value2) {
            addCriterion("unique_key_flg between", value1, value2, "uniqueKeyFlg");
            return (Criteria) this;
        }

        public Criteria andUniqueKeyFlgNotBetween(Boolean value1, Boolean value2) {
            addCriterion("unique_key_flg not between", value1, value2, "uniqueKeyFlg");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("update_user like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("update_user not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table column_master
     *
     * @mbg.generated do_not_delete_during_merge Fri Jan 22 13:43:20 JST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table column_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}