package jp.co.project.smart.autogen.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TableMasterExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table table_master
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table table_master
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table table_master
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_master
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	public TableMasterExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_master
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_master
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_master
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_master
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_master
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_master
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_master
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_master
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_master
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_master
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table table_master
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andTableIdIsNull() {
			addCriterion("table_id is null");
			return (Criteria) this;
		}

		public Criteria andTableIdIsNotNull() {
			addCriterion("table_id is not null");
			return (Criteria) this;
		}

		public Criteria andTableIdEqualTo(Integer value) {
			addCriterion("table_id =", value, "tableId");
			return (Criteria) this;
		}

		public Criteria andTableIdNotEqualTo(Integer value) {
			addCriterion("table_id <>", value, "tableId");
			return (Criteria) this;
		}

		public Criteria andTableIdGreaterThan(Integer value) {
			addCriterion("table_id >", value, "tableId");
			return (Criteria) this;
		}

		public Criteria andTableIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("table_id >=", value, "tableId");
			return (Criteria) this;
		}

		public Criteria andTableIdLessThan(Integer value) {
			addCriterion("table_id <", value, "tableId");
			return (Criteria) this;
		}

		public Criteria andTableIdLessThanOrEqualTo(Integer value) {
			addCriterion("table_id <=", value, "tableId");
			return (Criteria) this;
		}

		public Criteria andTableIdIn(List<Integer> values) {
			addCriterion("table_id in", values, "tableId");
			return (Criteria) this;
		}

		public Criteria andTableIdNotIn(List<Integer> values) {
			addCriterion("table_id not in", values, "tableId");
			return (Criteria) this;
		}

		public Criteria andTableIdBetween(Integer value1, Integer value2) {
			addCriterion("table_id between", value1, value2, "tableId");
			return (Criteria) this;
		}

		public Criteria andTableIdNotBetween(Integer value1, Integer value2) {
			addCriterion("table_id not between", value1, value2, "tableId");
			return (Criteria) this;
		}

		public Criteria andPhysicalNameIsNull() {
			addCriterion("physical_name is null");
			return (Criteria) this;
		}

		public Criteria andPhysicalNameIsNotNull() {
			addCriterion("physical_name is not null");
			return (Criteria) this;
		}

		public Criteria andPhysicalNameEqualTo(String value) {
			addCriterion("physical_name =", value, "physicalName");
			return (Criteria) this;
		}

		public Criteria andPhysicalNameNotEqualTo(String value) {
			addCriterion("physical_name <>", value, "physicalName");
			return (Criteria) this;
		}

		public Criteria andPhysicalNameGreaterThan(String value) {
			addCriterion("physical_name >", value, "physicalName");
			return (Criteria) this;
		}

		public Criteria andPhysicalNameGreaterThanOrEqualTo(String value) {
			addCriterion("physical_name >=", value, "physicalName");
			return (Criteria) this;
		}

		public Criteria andPhysicalNameLessThan(String value) {
			addCriterion("physical_name <", value, "physicalName");
			return (Criteria) this;
		}

		public Criteria andPhysicalNameLessThanOrEqualTo(String value) {
			addCriterion("physical_name <=", value, "physicalName");
			return (Criteria) this;
		}

		public Criteria andPhysicalNameLike(String value) {
			addCriterion("physical_name like", value, "physicalName");
			return (Criteria) this;
		}

		public Criteria andPhysicalNameNotLike(String value) {
			addCriterion("physical_name not like", value, "physicalName");
			return (Criteria) this;
		}

		public Criteria andPhysicalNameIn(List<String> values) {
			addCriterion("physical_name in", values, "physicalName");
			return (Criteria) this;
		}

		public Criteria andPhysicalNameNotIn(List<String> values) {
			addCriterion("physical_name not in", values, "physicalName");
			return (Criteria) this;
		}

		public Criteria andPhysicalNameBetween(String value1, String value2) {
			addCriterion("physical_name between", value1, value2, "physicalName");
			return (Criteria) this;
		}

		public Criteria andPhysicalNameNotBetween(String value1, String value2) {
			addCriterion("physical_name not between", value1, value2, "physicalName");
			return (Criteria) this;
		}

		public Criteria andLogicNameIsNull() {
			addCriterion("logic_name is null");
			return (Criteria) this;
		}

		public Criteria andLogicNameIsNotNull() {
			addCriterion("logic_name is not null");
			return (Criteria) this;
		}

		public Criteria andLogicNameEqualTo(String value) {
			addCriterion("logic_name =", value, "logicName");
			return (Criteria) this;
		}

		public Criteria andLogicNameNotEqualTo(String value) {
			addCriterion("logic_name <>", value, "logicName");
			return (Criteria) this;
		}

		public Criteria andLogicNameGreaterThan(String value) {
			addCriterion("logic_name >", value, "logicName");
			return (Criteria) this;
		}

		public Criteria andLogicNameGreaterThanOrEqualTo(String value) {
			addCriterion("logic_name >=", value, "logicName");
			return (Criteria) this;
		}

		public Criteria andLogicNameLessThan(String value) {
			addCriterion("logic_name <", value, "logicName");
			return (Criteria) this;
		}

		public Criteria andLogicNameLessThanOrEqualTo(String value) {
			addCriterion("logic_name <=", value, "logicName");
			return (Criteria) this;
		}

		public Criteria andLogicNameLike(String value) {
			addCriterion("logic_name like", value, "logicName");
			return (Criteria) this;
		}

		public Criteria andLogicNameNotLike(String value) {
			addCriterion("logic_name not like", value, "logicName");
			return (Criteria) this;
		}

		public Criteria andLogicNameIn(List<String> values) {
			addCriterion("logic_name in", values, "logicName");
			return (Criteria) this;
		}

		public Criteria andLogicNameNotIn(List<String> values) {
			addCriterion("logic_name not in", values, "logicName");
			return (Criteria) this;
		}

		public Criteria andLogicNameBetween(String value1, String value2) {
			addCriterion("logic_name between", value1, value2, "logicName");
			return (Criteria) this;
		}

		public Criteria andLogicNameNotBetween(String value1, String value2) {
			addCriterion("logic_name not between", value1, value2, "logicName");
			return (Criteria) this;
		}

		public Criteria andPrimaryKeyNameIsNull() {
			addCriterion("primary_key_name is null");
			return (Criteria) this;
		}

		public Criteria andPrimaryKeyNameIsNotNull() {
			addCriterion("primary_key_name is not null");
			return (Criteria) this;
		}

		public Criteria andPrimaryKeyNameEqualTo(String value) {
			addCriterion("primary_key_name =", value, "primaryKeyName");
			return (Criteria) this;
		}

		public Criteria andPrimaryKeyNameNotEqualTo(String value) {
			addCriterion("primary_key_name <>", value, "primaryKeyName");
			return (Criteria) this;
		}

		public Criteria andPrimaryKeyNameGreaterThan(String value) {
			addCriterion("primary_key_name >", value, "primaryKeyName");
			return (Criteria) this;
		}

		public Criteria andPrimaryKeyNameGreaterThanOrEqualTo(String value) {
			addCriterion("primary_key_name >=", value, "primaryKeyName");
			return (Criteria) this;
		}

		public Criteria andPrimaryKeyNameLessThan(String value) {
			addCriterion("primary_key_name <", value, "primaryKeyName");
			return (Criteria) this;
		}

		public Criteria andPrimaryKeyNameLessThanOrEqualTo(String value) {
			addCriterion("primary_key_name <=", value, "primaryKeyName");
			return (Criteria) this;
		}

		public Criteria andPrimaryKeyNameLike(String value) {
			addCriterion("primary_key_name like", value, "primaryKeyName");
			return (Criteria) this;
		}

		public Criteria andPrimaryKeyNameNotLike(String value) {
			addCriterion("primary_key_name not like", value, "primaryKeyName");
			return (Criteria) this;
		}

		public Criteria andPrimaryKeyNameIn(List<String> values) {
			addCriterion("primary_key_name in", values, "primaryKeyName");
			return (Criteria) this;
		}

		public Criteria andPrimaryKeyNameNotIn(List<String> values) {
			addCriterion("primary_key_name not in", values, "primaryKeyName");
			return (Criteria) this;
		}

		public Criteria andPrimaryKeyNameBetween(String value1, String value2) {
			addCriterion("primary_key_name between", value1, value2, "primaryKeyName");
			return (Criteria) this;
		}

		public Criteria andPrimaryKeyNameNotBetween(String value1, String value2) {
			addCriterion("primary_key_name not between", value1, value2, "primaryKeyName");
			return (Criteria) this;
		}

		public Criteria andTableOptionIsNull() {
			addCriterion("table_option is null");
			return (Criteria) this;
		}

		public Criteria andTableOptionIsNotNull() {
			addCriterion("table_option is not null");
			return (Criteria) this;
		}

		public Criteria andTableOptionEqualTo(String value) {
			addCriterion("table_option =", value, "tableOption");
			return (Criteria) this;
		}

		public Criteria andTableOptionNotEqualTo(String value) {
			addCriterion("table_option <>", value, "tableOption");
			return (Criteria) this;
		}

		public Criteria andTableOptionGreaterThan(String value) {
			addCriterion("table_option >", value, "tableOption");
			return (Criteria) this;
		}

		public Criteria andTableOptionGreaterThanOrEqualTo(String value) {
			addCriterion("table_option >=", value, "tableOption");
			return (Criteria) this;
		}

		public Criteria andTableOptionLessThan(String value) {
			addCriterion("table_option <", value, "tableOption");
			return (Criteria) this;
		}

		public Criteria andTableOptionLessThanOrEqualTo(String value) {
			addCriterion("table_option <=", value, "tableOption");
			return (Criteria) this;
		}

		public Criteria andTableOptionLike(String value) {
			addCriterion("table_option like", value, "tableOption");
			return (Criteria) this;
		}

		public Criteria andTableOptionNotLike(String value) {
			addCriterion("table_option not like", value, "tableOption");
			return (Criteria) this;
		}

		public Criteria andTableOptionIn(List<String> values) {
			addCriterion("table_option in", values, "tableOption");
			return (Criteria) this;
		}

		public Criteria andTableOptionNotIn(List<String> values) {
			addCriterion("table_option not in", values, "tableOption");
			return (Criteria) this;
		}

		public Criteria andTableOptionBetween(String value1, String value2) {
			addCriterion("table_option between", value1, value2, "tableOption");
			return (Criteria) this;
		}

		public Criteria andTableOptionNotBetween(String value1, String value2) {
			addCriterion("table_option not between", value1, value2, "tableOption");
			return (Criteria) this;
		}

		public Criteria andIndexesIsNull() {
			addCriterion("indexes is null");
			return (Criteria) this;
		}

		public Criteria andIndexesIsNotNull() {
			addCriterion("indexes is not null");
			return (Criteria) this;
		}

		public Criteria andIndexesEqualTo(Object value) {
			addCriterion("indexes =", value, "indexes");
			return (Criteria) this;
		}

		public Criteria andIndexesNotEqualTo(Object value) {
			addCriterion("indexes <>", value, "indexes");
			return (Criteria) this;
		}

		public Criteria andIndexesGreaterThan(Object value) {
			addCriterion("indexes >", value, "indexes");
			return (Criteria) this;
		}

		public Criteria andIndexesGreaterThanOrEqualTo(Object value) {
			addCriterion("indexes >=", value, "indexes");
			return (Criteria) this;
		}

		public Criteria andIndexesLessThan(Object value) {
			addCriterion("indexes <", value, "indexes");
			return (Criteria) this;
		}

		public Criteria andIndexesLessThanOrEqualTo(Object value) {
			addCriterion("indexes <=", value, "indexes");
			return (Criteria) this;
		}

		public Criteria andIndexesIn(List<Object> values) {
			addCriterion("indexes in", values, "indexes");
			return (Criteria) this;
		}

		public Criteria andIndexesNotIn(List<Object> values) {
			addCriterion("indexes not in", values, "indexes");
			return (Criteria) this;
		}

		public Criteria andIndexesBetween(Object value1, Object value2) {
			addCriterion("indexes between", value1, value2, "indexes");
			return (Criteria) this;
		}

		public Criteria andIndexesNotBetween(Object value1, Object value2) {
			addCriterion("indexes not between", value1, value2, "indexes");
			return (Criteria) this;
		}

		public Criteria andComplexUniqueKeyListIsNull() {
			addCriterion("complex_unique_key_list is null");
			return (Criteria) this;
		}

		public Criteria andComplexUniqueKeyListIsNotNull() {
			addCriterion("complex_unique_key_list is not null");
			return (Criteria) this;
		}

		public Criteria andComplexUniqueKeyListEqualTo(Object value) {
			addCriterion("complex_unique_key_list =", value, "complexUniqueKeyList");
			return (Criteria) this;
		}

		public Criteria andComplexUniqueKeyListNotEqualTo(Object value) {
			addCriterion("complex_unique_key_list <>", value, "complexUniqueKeyList");
			return (Criteria) this;
		}

		public Criteria andComplexUniqueKeyListGreaterThan(Object value) {
			addCriterion("complex_unique_key_list >", value, "complexUniqueKeyList");
			return (Criteria) this;
		}

		public Criteria andComplexUniqueKeyListGreaterThanOrEqualTo(Object value) {
			addCriterion("complex_unique_key_list >=", value, "complexUniqueKeyList");
			return (Criteria) this;
		}

		public Criteria andComplexUniqueKeyListLessThan(Object value) {
			addCriterion("complex_unique_key_list <", value, "complexUniqueKeyList");
			return (Criteria) this;
		}

		public Criteria andComplexUniqueKeyListLessThanOrEqualTo(Object value) {
			addCriterion("complex_unique_key_list <=", value, "complexUniqueKeyList");
			return (Criteria) this;
		}

		public Criteria andComplexUniqueKeyListIn(List<Object> values) {
			addCriterion("complex_unique_key_list in", values, "complexUniqueKeyList");
			return (Criteria) this;
		}

		public Criteria andComplexUniqueKeyListNotIn(List<Object> values) {
			addCriterion("complex_unique_key_list not in", values, "complexUniqueKeyList");
			return (Criteria) this;
		}

		public Criteria andComplexUniqueKeyListBetween(Object value1, Object value2) {
			addCriterion("complex_unique_key_list between", value1, value2, "complexUniqueKeyList");
			return (Criteria) this;
		}

		public Criteria andComplexUniqueKeyListNotBetween(Object value1, Object value2) {
			addCriterion("complex_unique_key_list not between", value1, value2, "complexUniqueKeyList");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNull() {
			addCriterion("create_user is null");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNotNull() {
			addCriterion("create_user is not null");
			return (Criteria) this;
		}

		public Criteria andCreateUserEqualTo(String value) {
			addCriterion("create_user =", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotEqualTo(String value) {
			addCriterion("create_user <>", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThan(String value) {
			addCriterion("create_user >", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
			addCriterion("create_user >=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThan(String value) {
			addCriterion("create_user <", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThanOrEqualTo(String value) {
			addCriterion("create_user <=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLike(String value) {
			addCriterion("create_user like", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotLike(String value) {
			addCriterion("create_user not like", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserIn(List<String> values) {
			addCriterion("create_user in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotIn(List<String> values) {
			addCriterion("create_user not in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserBetween(String value1, String value2) {
			addCriterion("create_user between", value1, value2, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotBetween(String value1, String value2) {
			addCriterion("create_user not between", value1, value2, "createUser");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("update_time not between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIsNull() {
			addCriterion("update_user is null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIsNotNull() {
			addCriterion("update_user is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserEqualTo(String value) {
			addCriterion("update_user =", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotEqualTo(String value) {
			addCriterion("update_user <>", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserGreaterThan(String value) {
			addCriterion("update_user >", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
			addCriterion("update_user >=", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLessThan(String value) {
			addCriterion("update_user <", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLessThanOrEqualTo(String value) {
			addCriterion("update_user <=", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLike(String value) {
			addCriterion("update_user like", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotLike(String value) {
			addCriterion("update_user not like", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIn(List<String> values) {
			addCriterion("update_user in", values, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotIn(List<String> values) {
			addCriterion("update_user not in", values, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserBetween(String value1, String value2) {
			addCriterion("update_user between", value1, value2, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotBetween(String value1, String value2) {
			addCriterion("update_user not between", value1, value2, "updateUser");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table table_master
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table table_master
     *
     * @mbg.generated do_not_delete_during_merge Wed Jan 20 13:15:24 JST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}