package jp.co.project.smart.autogen.model;

import java.util.Date;

public class TableMaster {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_master.table_id
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	private Integer tableId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_master.physical_name
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	private String physicalName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_master.logic_name
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	private String logicName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_master.primary_key_name
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	private String primaryKeyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_master.table_option
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	private String tableOption;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_master.indexes
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	private Object indexes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_master.complex_unique_key_list
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	private Object complexUniqueKeyList;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_master.create_time
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_master.create_user
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	private String createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_master.update_time
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_master.update_user
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	private String updateUser;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_master.table_id
	 * @return  the value of table_master.table_id
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	public Integer getTableId() {
		return tableId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_master.table_id
	 * @param tableId  the value for table_master.table_id
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	public void setTableId(Integer tableId) {
		this.tableId = tableId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_master.physical_name
	 * @return  the value of table_master.physical_name
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	public String getPhysicalName() {
		return physicalName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_master.physical_name
	 * @param physicalName  the value for table_master.physical_name
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	public void setPhysicalName(String physicalName) {
		this.physicalName = physicalName == null ? null : physicalName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_master.logic_name
	 * @return  the value of table_master.logic_name
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	public String getLogicName() {
		return logicName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_master.logic_name
	 * @param logicName  the value for table_master.logic_name
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	public void setLogicName(String logicName) {
		this.logicName = logicName == null ? null : logicName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_master.primary_key_name
	 * @return  the value of table_master.primary_key_name
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	public String getPrimaryKeyName() {
		return primaryKeyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_master.primary_key_name
	 * @param primaryKeyName  the value for table_master.primary_key_name
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	public void setPrimaryKeyName(String primaryKeyName) {
		this.primaryKeyName = primaryKeyName == null ? null : primaryKeyName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_master.table_option
	 * @return  the value of table_master.table_option
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	public String getTableOption() {
		return tableOption;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_master.table_option
	 * @param tableOption  the value for table_master.table_option
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	public void setTableOption(String tableOption) {
		this.tableOption = tableOption == null ? null : tableOption.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_master.indexes
	 * @return  the value of table_master.indexes
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	public Object getIndexes() {
		return indexes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_master.indexes
	 * @param indexes  the value for table_master.indexes
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	public void setIndexes(Object indexes) {
		this.indexes = indexes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_master.complex_unique_key_list
	 * @return  the value of table_master.complex_unique_key_list
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	public Object getComplexUniqueKeyList() {
		return complexUniqueKeyList;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_master.complex_unique_key_list
	 * @param complexUniqueKeyList  the value for table_master.complex_unique_key_list
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	public void setComplexUniqueKeyList(Object complexUniqueKeyList) {
		this.complexUniqueKeyList = complexUniqueKeyList;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_master.create_time
	 * @return  the value of table_master.create_time
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_master.create_time
	 * @param createTime  the value for table_master.create_time
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_master.create_user
	 * @return  the value of table_master.create_user
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_master.create_user
	 * @param createUser  the value for table_master.create_user
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser == null ? null : createUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_master.update_time
	 * @return  the value of table_master.update_time
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_master.update_time
	 * @param updateTime  the value for table_master.update_time
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_master.update_user
	 * @return  the value of table_master.update_user
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_master.update_user
	 * @param updateUser  the value for table_master.update_user
	 * @mbg.generated  Wed Jan 20 13:39:44 JST 2021
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser == null ? null : updateUser.trim();
	}
}