package jp.co.project.smart.autogen.model;

import java.util.Date;

public class WordDictionary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_dictionary.word_id
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private Integer wordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_dictionary.word_length
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private Integer wordLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_dictionary.word_decimal
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private Integer wordDecimal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_dictionary.array_flg
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private Boolean arrayFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_dictionary.array_dimension
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private Integer arrayDimension;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_dictionary.description
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_dictionary.logic_name
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private String logicName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_dictionary.physical_name
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private String physicalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_dictionary.word_type
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private String wordType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_dictionary.create_time
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_dictionary.create_user
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_dictionary.update_time
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_dictionary.update_user
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_dictionary.word_id
     *
     * @return the value of word_dictionary.word_id
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public Integer getWordId() {
        return wordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_dictionary.word_id
     *
     * @param wordId the value for word_dictionary.word_id
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setWordId(Integer wordId) {
        this.wordId = wordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_dictionary.word_length
     *
     * @return the value of word_dictionary.word_length
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public Integer getWordLength() {
        return wordLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_dictionary.word_length
     *
     * @param wordLength the value for word_dictionary.word_length
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setWordLength(Integer wordLength) {
        this.wordLength = wordLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_dictionary.word_decimal
     *
     * @return the value of word_dictionary.word_decimal
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public Integer getWordDecimal() {
        return wordDecimal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_dictionary.word_decimal
     *
     * @param wordDecimal the value for word_dictionary.word_decimal
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setWordDecimal(Integer wordDecimal) {
        this.wordDecimal = wordDecimal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_dictionary.array_flg
     *
     * @return the value of word_dictionary.array_flg
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public Boolean getArrayFlg() {
        return arrayFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_dictionary.array_flg
     *
     * @param arrayFlg the value for word_dictionary.array_flg
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setArrayFlg(Boolean arrayFlg) {
        this.arrayFlg = arrayFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_dictionary.array_dimension
     *
     * @return the value of word_dictionary.array_dimension
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public Integer getArrayDimension() {
        return arrayDimension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_dictionary.array_dimension
     *
     * @param arrayDimension the value for word_dictionary.array_dimension
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setArrayDimension(Integer arrayDimension) {
        this.arrayDimension = arrayDimension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_dictionary.description
     *
     * @return the value of word_dictionary.description
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_dictionary.description
     *
     * @param description the value for word_dictionary.description
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_dictionary.logic_name
     *
     * @return the value of word_dictionary.logic_name
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public String getLogicName() {
        return logicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_dictionary.logic_name
     *
     * @param logicName the value for word_dictionary.logic_name
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setLogicName(String logicName) {
        this.logicName = logicName == null ? null : logicName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_dictionary.physical_name
     *
     * @return the value of word_dictionary.physical_name
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public String getPhysicalName() {
        return physicalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_dictionary.physical_name
     *
     * @param physicalName the value for word_dictionary.physical_name
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setPhysicalName(String physicalName) {
        this.physicalName = physicalName == null ? null : physicalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_dictionary.word_type
     *
     * @return the value of word_dictionary.word_type
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public String getWordType() {
        return wordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_dictionary.word_type
     *
     * @param wordType the value for word_dictionary.word_type
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setWordType(String wordType) {
        this.wordType = wordType == null ? null : wordType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_dictionary.create_time
     *
     * @return the value of word_dictionary.create_time
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_dictionary.create_time
     *
     * @param createTime the value for word_dictionary.create_time
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_dictionary.create_user
     *
     * @return the value of word_dictionary.create_user
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_dictionary.create_user
     *
     * @param createUser the value for word_dictionary.create_user
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_dictionary.update_time
     *
     * @return the value of word_dictionary.update_time
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_dictionary.update_time
     *
     * @param updateTime the value for word_dictionary.update_time
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_dictionary.update_user
     *
     * @return the value of word_dictionary.update_user
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_dictionary.update_user
     *
     * @param updateUser the value for word_dictionary.update_user
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }
}