package jp.co.project.smart.autogen.mapper;

import java.util.List;
import jp.co.project.smart.autogen.model.ApiDefine;
import jp.co.project.smart.autogen.model.ApiDefineExample;
import org.apache.ibatis.annotations.Param;

public interface ApiDefineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_define
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    long countByExample(ApiDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_define
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    int deleteByExample(ApiDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_define
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    int deleteByPrimaryKey(String apiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_define
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    int insert(ApiDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_define
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    int insertSelective(ApiDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_define
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    List<ApiDefine> selectByExample(ApiDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_define
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    ApiDefine selectByPrimaryKey(String apiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_define
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    int updateByExampleSelective(@Param("record") ApiDefine record, @Param("example") ApiDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_define
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    int updateByExample(@Param("record") ApiDefine record, @Param("example") ApiDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_define
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    int updateByPrimaryKeySelective(ApiDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_define
     *
     * @mbg.generated Thu Mar 11 17:42:57 JST 2021
     */
    int updateByPrimaryKey(ApiDefine record);
}