package jp.co.project.smart.autogen.mapper;

import java.util.List;
import jp.co.project.smart.autogen.model.CodeValueMaster;
import jp.co.project.smart.autogen.model.CodeValueMasterExample;
import org.apache.ibatis.annotations.Param;

public interface CodeValueMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_value_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    long countByExample(CodeValueMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_value_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    int deleteByExample(CodeValueMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_value_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    int deleteByPrimaryKey(Integer codeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_value_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    int insert(CodeValueMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_value_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    int insertSelective(CodeValueMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_value_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    List<CodeValueMaster> selectByExample(CodeValueMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_value_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    CodeValueMaster selectByPrimaryKey(Integer codeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_value_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    int updateByExampleSelective(@Param("record") CodeValueMaster record, @Param("example") CodeValueMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_value_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    int updateByExample(@Param("record") CodeValueMaster record, @Param("example") CodeValueMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_value_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    int updateByPrimaryKeySelective(CodeValueMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_value_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    int updateByPrimaryKey(CodeValueMaster record);
}