package jp.co.project.smart.autogen.mapper;

import java.util.List;
import jp.co.project.smart.autogen.model.CodeMaster;
import jp.co.project.smart.autogen.model.CodeMasterExample;
import org.apache.ibatis.annotations.Param;

public interface CodeMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    long countByExample(CodeMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    int deleteByExample(CodeMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    int deleteByPrimaryKey(Integer codeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    int insert(CodeMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    int insertSelective(CodeMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    List<CodeMaster> selectByExample(CodeMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    CodeMaster selectByPrimaryKey(Integer codeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    int updateByExampleSelective(@Param("record") CodeMaster record, @Param("example") CodeMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    int updateByExample(@Param("record") CodeMaster record, @Param("example") CodeMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    int updateByPrimaryKeySelective(CodeMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    int updateByPrimaryKey(CodeMaster record);
}