package jp.co.project.smart.autogen.mapper;

import java.util.List;
import jp.co.project.smart.autogen.model.ColumnMaster;
import jp.co.project.smart.autogen.model.ColumnMasterExample;
import org.apache.ibatis.annotations.Param;

public interface ColumnMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    long countByExample(ColumnMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    int deleteByExample(ColumnMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    int deleteByPrimaryKey(Integer columnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    int insert(ColumnMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    int insertSelective(ColumnMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    List<ColumnMaster> selectByExample(ColumnMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    ColumnMaster selectByPrimaryKey(Integer columnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    int updateByExampleSelective(@Param("record") ColumnMaster record, @Param("example") ColumnMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    int updateByExample(@Param("record") ColumnMaster record, @Param("example") ColumnMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    int updateByPrimaryKeySelective(ColumnMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_master
     *
     * @mbg.generated Fri Jan 22 13:43:20 JST 2021
     */
    int updateByPrimaryKey(ColumnMaster record);
}